### PR TITLE
Share file by Twake navigation (1302)

### PR DESCRIPTION
**Pull request by huynguyennovem**
https://user-images.githubusercontent.com/29337364/158311478-987cff50-2f78-46ba-804b-fcbfd27983b8.mp4

### CODE REVIEW

**Comment by EvGen94** [comment]
I have one question, we get too much delay after the Done uploading, it takes to navigate 3.5 sec it is too much , but actual delay is - milliseconds: 1000, what do you think?

**Review by EvGen94 — APPROVED** [review]

**Comment by huynguyennovem** [comment]
> I have one question, we get too much delay after the Done uploading, it takes to navigate 3.5 sec it is too much , but actual delay is - milliseconds: 1000, what do you think?

Actually, after the 1000ms delay, we invoke `navigateToChannelAfterSharedFile` that will do many functions (fetch and select company, workspace, channel) to make sure we can navigate to destination.

**Comment by EvGen94** [comment]
> > I have one question, we get too much delay after the Done uploading, it takes to navigate 3.5 sec it is too much , but actual delay is - milliseconds: 1000, what do you think?
> 
> Actually, after the 1000ms delay, we invoke `navigateToChannelAfterSharedFile` that will do many functions (fetch and select company, workspace, channel) to make sure we can navigate to destination.

Let's do 0.5 sec then

**Comment by huynguyennovem** [comment]
> > > I have one question, we get too much delay after the Done uploading, it takes to navigate 3.5 sec it is too much , but actual delay is - milliseconds: 1000, what do you think?
> > 
> > 
> > Actually, after the 1000ms delay, we invoke `navigateToChannelAfterSharedFile` that will do many functions (fetch and select company, workspace, channel) to make sure we can navigate to destination.
> 
> Let's do 0.5 sec then

Updated to 0.5s

**Pull request merged**
